### ISSUE TITLE
Add keyword to fetch elements computed css style

### ISSUE THREAD

**Issue by rasjani** [MarketSquare/robotframework-seleniumtestability#23]
https://adiralashivaprasad.blogspot.com/2018/05/how-to-get-css-attribute-value-in-robot.html

**Comment by idxn** [comment]
Does WebElement.value_of_css_property not returned the computed style?

https://seleniumhq.github.io/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webelement.html?highlight=value_of_css_property#selenium.webdriver.remote.webelement.WebElement.value_of_css_property
