### ISSUE TITLE
Add support for Touch events

### ISSUE THREAD

**Issue by rasjani** [MarketSquare/robotframework-seleniumtestability#7]
Webdriver spec has commands to generate touch events but SeleniumLibrary doesn't support these yet.  Implement in Testability

**Comment by AlphaRoy14** [comment]
Hey! I was just wondering is the function should return a TouchAction object or different actions based on the parameter?

**Comment by rasjani** [comment]
I have not thought this so much yet - api docs are here: https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.touch_actions

I'd assume that SeleniumTestability should provide high level keywords based on that api and do a TouchAction object which is executed by perform() and then if there are any return values, return those and rethrow the exceptions if things go south..
