### ISSUE TITLE
Versioneer code in the repo will not work with 3.12 python.

### ISSUE THREAD

**Issue by rasjani** [MarketSquare/robotframework-seleniumtestability#75]
SafeConfigParser that versioneer uses was removed with 3.12 python release so installation from source code will not work.

**Comment by rasjani** [comment]
https://github.com/python-versioneer/python-versioneer/issues/375

**Comment by effigies** [comment]
The versioneer issue is resolved, but an old versioneer is vendored here. Upgrade with `pipx run versioneer install`.

See https://github.com/python-versioneer/python-versioneer/blob/master/UPGRADING.md for any migration issues.

**Comment by rasjani** [comment]
> The versioneer issue is resolved, but an old versioneer is vendored here. Upgrade with `pipx run versioneer install`.
> 
> 
> 
> See https://github.com/python-versioneer/python-versioneer/blob/master/UPGRADING.md for any migration issues.



Everything in this repo is written by  me - except versioneer - and i applied the fix with this patch. Rest can stay as-is as nobody wont be updating this project anyway
