### ISSUE TITLE
Consider supporting Angular & React

### ISSUE THREAD

**Issue by rasjani** [MarketSquare/robotframework-seleniumtestability#9]
Supporting angular should add waits for angular & angularjs and custom locators.

**Comment by asyrjasalo** [comment]
What would be the advantage over using [robotframework-angularjs](https://github.com/Selenium2Library/robotframework-angularjs) or [robotframework-react](https://github.com/kitconcept/robotframework-react)?

**Comment by rasjani** [comment]
extra features this project and less dependencies. Also, ed has explicitly said that "new plugin api" doesn't help and personally i disagree. A lot of code could be shaved from current angularjs codebase with seleniumlibrary's plugin api.. 

Also, one usecase  - to which i've even stumbled on my own:  real world applications might mix angular and non-angular apps which makes the testing a bit cumbersome when you have to dig into multiple libraries.

**Comment by idxn** [comment]
@rasjani should we split this into 2 or more issue? 
e.g. 
* supporting for angular
* supporting for react

**Comment by rasjani** [comment]
definitely... This was more like "epic" ticket if it would raise any interest.
